function show_practice_screen()
%%
% show_practice_screen(...)
%
% Author:Kara & Ken
% Project: DSP
%
% Description:
%   Displays information to the patient while they are trying to repeat the
%   memorized sequence.
%
% Inputs:   NONE
%
% Outputs:  NONE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


dim1 = [0.125,0.5,0.75,0.1];
str1 = {'Verify';...
    '';...
    '';...
    'Please repeatedly type the sequence slowly and as accurately as possible';...
    'until you complete three correct repetitions in a row.'};...
% '';...
% '';...
% 'This screen will automatically update once you have typed the sequence correctly three times in a row.'};
annotation('textbox',dim1,'String',str1,...
    'FontName','Arial','FontSize',36,...
    'EdgeColor','none',...
    'HorizontalAlignment','center','VerticalAlignment','middle');
end